version: '3.8'

services:
  app:
    build: .
    container_name: fyle-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=core/server.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000
